name: EmmersonFrontend CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/emmerson.pl-frontend:latest

      - name: Execute SSH commmands on remote server
        uses: JimCronqvist/action-ssh@master
        env:
          NAME: "Root"
        with:
          hosts: 'root@backend.emmerson.pl'
          privateKey: ${{ secrets.EXECUTE_SSH_KEY }}
          debug: false
          command: |
            cd /www/docker
            docker-compose pull carriera/emmerson.pl-frontend:latest
            docker-compose stop frontend
            docker-compose rm -f frontend
            docker-compose up -d frontend

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
